# wrangler.toml
name = '0n0'
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "STATIC_ASSETS"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "69297e0b-6da4-4cb8-b349-80891d0fbb4a"
